meta_product_name: "Synopsix"
meta_title: "Synopsix - An addictive game for movie fans"
meta_description: "Choose a game mode and try to discover the Movie's title "
meta_image: "meta-img.png" # should exist in `app/assets/images/`
twitter_account: "@Lewagonparis"   # required for Twitter Cards
